services:
  devinedesk:
    build: .
    container_name: devinedesk
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/devinedesk?schema=public
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:15-alpine
    container_name: devinedesk_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devinedesk
    ports:
      - "5434:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: devinedesk_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata:
  pgdata2:
